# Generated by Django 5.2.3 on 2025-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
    ]
